export const CREATE_MAZE_REQUEST = "CREATE_MAZE_REQUEST";
export const CREATE_MAZE_SUCCESS = "CREATE_MAZE_SUCCESS";
export const CREATE_MAZE_FAILURE = "CREATE_MAZE_FAILURE";

export const GET_MAZE_REQUEST = "GET_MAZE_REQUEST";
export const GET_MAZE_SUCCESS = "GET_MAZE_SUCCESS";
export const GET_MAZE_FAILURE = "GET_MAZE_FAILURE";

export const RESET_MAZE = "RESET_MAZE";
